---
title: Yu-Shiang Wong

description:  |
  I obtained my Ph.D. at University College London, advised by <a href="http://www0.cs.ucl.ac.uk/staff/n.mitra/index.html">Prof. Niloy J Mitra</a>, as a member of the <a href="http://geometry.cs.ucl.ac.uk/index.php" >SmartGeometry group</a>. During my Ph.D., I focused on dynamic scene reconstruction and collaborated with <a href="https://niessnerlab.org/index.html">Prof. Matthias Nießner</a>.
  
  Before that, I worked as a Research Assitant at Academia Sinica in Taiwan, supervised by <a href="https://homepage.iis.sinica.edu.tw/pages/kysu/vita_en.html">Prof. Su, Keh-Yih</a>. I completed my Master’s in Computer Science at National Tsing Hua University, at <a href="https://cgv.cs.nthu.edu.tw/">CGV Lab</a>, supervised by <a href="https://cgv.cs.nthu.edu.tw/hkchu/" >Prof. Hung-Kuo Chu</a>. 
  
  My research interests include Neural representation, 3D/4D reconstruction, synthetic environment, and generative modeling.
head: images/head.jpg
email: yushiangwtw@gmail.com
linkedin: https://www.linkedin.com/in/yswong
githuburl: https://github.com/yushiangw
cvurl: https://drive.google.com/file/d/1-6hyAq4A-n-OIopQfOCHOKZuKJj9BzS7/view?usp=sharing
google_analytics: G-SNM63CV423
show_downloads: false
theme: jekyll-theme-minimal
gems:
  - jekyll-mentions
